version: "3.8"

services:
  moondream:
    image: ros-moondream-gaze:latest
    container_name: moondream_container
    runtime: nvidia  # Enables GPU support (requires NVIDIA Container Toolkit)
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./src/gaze_detection:/workspace/src/gaze_detection
      - ./check_setup.sh:/workspace/check_setup.sh
      - ./setup_ros_env.sh:/workspace/setup_ros_env.sh
    working_dir: /workspace
    command: >
      bash -c "
      chmod +x /workspace/check_setup.sh &&
      chmod +x /workspace/setup_ros_env.sh &&
      /workspace/check_setup.sh &&
      /workspace/setup_ros_env.sh &&
      exec bash"
    stdin_open: true
    tty: true
    restart: "no"
